"""fixed indexes for ingestion table

Revision ID: 172bf7bfe5fa
Revises: a3156b29f7e0
Create Date: 2026-07-03 15:49:31.315773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172bf7bfe5fa'
down_revision: Union[str, Sequence[str], None] = 'a3156b29f7e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_airport_status'), table_name='ingested_files')
    op.drop_index(op.f('ix_ingested_files_airport_code'), table_name='ingested_files')
    op.create_index(op.f('ix_ingested_files_status'), 'ingested_files', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingested_files_status'), table_name='ingested_files')
    op.create_index(op.f('ix_ingested_files_airport_code'), 'ingested_files', ['airport_code'], unique=False)
    op.create_index(op.f('idx_airport_status'), 'ingested_files', ['airport_code', 'status'], unique=False)
    # ### end Alembic commands ###
