"""weather code mapping table

Revision ID: 28bc2f388d48
Revises: 28a816ffc097
Create Date: 2026-07-04 19:12:14.285718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28bc2f388d48'
down_revision: Union[str, Sequence[str], None] = '28a816ffc097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_codes',
    sa.Column('weather_code', sa.Integer(), nullable=False),
    sa.Column('weather_description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('weather_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_codes')
    # ### end Alembic commands ###
