"""weather code mappings

Revision ID: f8e176f94221
Revises: 28bc2f388d48
Create Date: 2026-07-04 19:12:54.496351

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8e176f94221"
down_revision: Union[str, Sequence[str], None] = "28bc2f388d48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

wmo_codes = {
    0: "Clear sky",
    1: "Mainly clear",
    2: "Partly cloudy",
    3: "Overcast",
    45: "Fog",
    48: "Depositing rime fog",
    51: "Drizzle: Light intensity",
    53: "Drizzle: Moderate intensity",
    55: "Drizzle: Dense intensity",
    56: "Freezing Drizzle: Light intensity",
    57: "Freezing Drizzle: Dense intensity",
    61: "Rain: Slight intensity",
    63: "Rain: Moderate intensity",
    65: "Rain: Heavy intensity",
    66: "Freezing Rain: Light intensity",
    67: "Freezing Rain: Heavy intensity",
    71: "Snow fall: Slight intensity",
    73: "Snow fall: Moderate intensity",
    75: "Snow fall: Heavy intensity",
    77: "Snow grains",
    80: "Rain showers: Slight",
    81: "Rain showers: Moderate",
    82: "Rain showers: Violent",
    85: "Snow showers: Slight",
    86: "Snow showers: Heavy",
    95: "Thunderstorm: Slight or moderate",
    96: "Thunderstorm with slight hail",
    99: "Thunderstorm with heavy hail",
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    weather_codes_table = sa.table(
        "weather_codes",
        sa.column("weather_code", sa.Integer),
        sa.column("weather_description", sa.String),
    )

    formatted_rows = [
        {"weather_code": code, "weather_description": description}
        for code, description in wmo_codes.items()
    ]
    op.bulk_insert(weather_codes_table, formatted_rows)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    target_keys = tuple(wmo_codes.keys())

    op.execute(f"DELETE FROM weather_codes WHERE weather_code IN {target_keys}")
    # ### end Alembic commands ###
