"""seed data

Revision ID: 28a816ffc097
Revises: fa909d9d44aa
Create Date: 2026-07-04 16:09:25.870320

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28a816ffc097"
down_revision: Union[str, Sequence[str], None] = "fa909d9d44aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

raw_data = {
    "cities": [
        {
            "airport_code": "LAX",
            "city": "Los Angeles",
            "state": "CA",
            "lat": 33.942791,
            "lon": -118.410042,
            "timezone": "America/Los_Angeles",
        },
        {
            "airport_code": "SFO",
            "city": "San Francisco",
            "state": "CA",
            "lat": 37.615223,
            "lon": -122.389977,
            "timezone": "America/Los_Angeles",
        },
        {
            "airport_code": "LAS",
            "city": "Las Vegas",
            "state": "NV",
            "lat": 36.08601,
            "lon": -115.153969,
            "timezone": "America/Los_Angeles",
        },
    ]
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    locations_table = sa.table(
        "locations",
        sa.column("airport_code", sa.String),
        sa.column("city", sa.String),
        sa.column("state", sa.String),
        sa.column("latitude", sa.Numeric),
        sa.column("longitude", sa.Numeric),
        sa.column("timezone", sa.String),
    )

    formatted_rows = [
        {
            "airport_code": item["airport_code"],
            "city": item["city"],
            "state": item["state"],
            "latitude": item["lat"],
            "longitude": item["lon"],
            "timezone": item["timezone"],
        }
        for item in raw_data["cities"]
    ]
    op.bulk_insert(locations_table, formatted_rows)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM locations WHERE airport_code IN ('LAX', 'SFO', 'LAS')")
    # ### end Alembic commands ###
