"""materialized views

Revision ID: 603c16cf2078
Revises: c8923043aabf
Create Date: 2026-07-07 16:00:39.215455

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "603c16cf2078"
down_revision: Union[str, Sequence[str], None] = "c8923043aabf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Weekly aggregated metrics view
    op.execute("""
    CREATE MATERIALIZED VIEW mv_weekly_weather AS
    SELECT
	dw.airport_code,
	d.year_int,
	d.week_of_year,
	ROUND(AVG(dw.temperature_2m_mean_celsius), 2) AS temp_mean,
	ROUND(AVG(dw.temperature_2m_max_celsius), 2) AS temp_max,
	ROUND(AVG(dw.temperature_2m_min_celsius), 2) AS temp_min,
	
	ROUND(AVG(dw.wind_speed_10m_mean_kmh), 2) AS wind_speed_mean,
	ROUND(AVG(dw.wind_speed_10m_max_kmh), 2) AS wind_speed_max,
	ROUND(AVG(dw.wind_speed_10m_min_kmh), 2) AS wind_speed_min,
	
	ROUND(AVG(dw.wind_gusts_10m_mean_kmh), 2) AS wind_gusts_mean,
	ROUND(AVG(dw.wind_gusts_10m_max_kmh), 2) AS wind_gusts_max,
	ROUND(AVG(dw.wind_gusts_10m_min_kmh), 2) AS wind_gusts_min,
	
	ROUND(SUM(dw.precipitation_sum_mm), 2) AS precipitation_sum,
	SUM(dw.precipitation_hours) AS precipitation_hours
FROM daily_weather_metrics dw
JOIN date_dimension d ON dw.weather_date = d.weather_date
GROUP BY dw.airport_code, d.year_int, d.week_of_year;
    """)
    op.execute(
        "CREATE UNIQUE INDEX idx_mv_weekly ON mv_weekly_weather (airport_code, year_int, week_of_year);"
    )

    # Monthly aggregated metrics view
    op.execute("""CREATE MATERIALIZED VIEW mv_monthly_weather AS
SELECT
	dw.airport_code,
	d.year_int,
	d.month_int,
	ROUND(AVG(dw.temperature_2m_mean_celsius), 2) AS temp_mean,
	ROUND(AVG(dw.temperature_2m_max_celsius), 2) AS temp_max,
	ROUND(AVG(dw.temperature_2m_min_celsius), 2) AS temp_min,
	
	ROUND(AVG(dw.wind_speed_10m_mean_kmh), 2) AS wind_speed_mean,
	ROUND(AVG(dw.wind_speed_10m_max_kmh), 2) AS wind_speed_max,
	ROUND(AVG(dw.wind_speed_10m_min_kmh), 2) AS wind_speed_min,
	
	ROUND(AVG(dw.wind_gusts_10m_mean_kmh), 2) AS wind_gusts_mean,
	ROUND(AVG(dw.wind_gusts_10m_max_kmh), 2) AS wind_gusts_max,
	ROUND(AVG(dw.wind_gusts_10m_min_kmh), 2) AS wind_gusts_min,
	
	ROUND(SUM(dw.precipitation_sum_mm), 2) AS precipitation_sum,
	SUM(dw.precipitation_hours) AS precipitation_hours
FROM daily_weather_metrics dw
JOIN date_dimension d ON dw.weather_date = d.weather_date
GROUP BY dw.airport_code, d.year_int, d.month_int;""")

    op.execute(
        "CREATE UNIQUE INDEX idx_mv_monthly ON mv_monthly_weather (airport_code, year_int, month_int);"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP MATERIALIZED VIEW IF EXISTS mv_weekly_weather CASCADE;")
    op.execute("DROP MATERIALIZED VIEW IF EXISTS mv_monthly_weather CASCADE;")
    # ### end Alembic commands ###
