"""date + weather metrics table

Revision ID: c8923043aabf
Revises: f8e176f94221
Create Date: 2026-07-05 12:59:33.381811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8923043aabf'
down_revision: Union[str, Sequence[str], None] = 'f8e176f94221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date_dimension',
    sa.Column('weather_date', sa.Date(), nullable=False),
    sa.Column('epoch_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('day_of_week_int', sa.Integer(), nullable=False, comment='1 (Monday) to 7 (Sunday)'),
    sa.Column('day_of_week_name', sa.String(length=9), nullable=False, comment="'Monday', 'Tuesday'"),
    sa.Column('day_of_year', sa.Integer(), nullable=False, comment='1 to 366'),
    sa.Column('week_of_year', sa.Integer(), nullable=False, comment='1 to 53'),
    sa.Column('month_int', sa.Integer(), nullable=False, comment='1 to 12'),
    sa.Column('month_name', sa.String(length=9), nullable=False, comment="'January', 'February'"),
    sa.Column('quarter', sa.Integer(), nullable=False, comment='1 to 4'),
    sa.Column('year_int', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('weather_date')
    )
    op.create_table('daily_weather_metrics',
    sa.Column('airport_code', sa.String(length=10), nullable=False),
    sa.Column('weather_date', sa.Date(), nullable=False),
    sa.Column('weather_code', sa.Integer(), nullable=False),
    sa.Column('temperature_2m_mean_celsius', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('temperature_2m_max_celsius', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('temperature_2m_min_celsius', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('dew_point_2m_mean_celsius', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('wind_speed_10m_mean_kmh', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_speed_10m_max_kmh', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_speed_10m_min_kmh', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_gusts_10m_mean_kmh', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_gusts_10m_max_kmh', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_gusts_10m_min_kmh', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('precipitation_sum_mm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('precipitation_hours', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('cloud_cover_mean_percent', sa.Integer(), nullable=True),
    sa.Column('relative_humidity_2m_mean_percent', sa.Integer(), nullable=True),
    sa.Column('daylight_duration_sec', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['airport_code'], ['locations.airport_code'], name='locations_airport_code_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weather_code'], ['weather_codes.weather_code'], name='weather_codes_weather_code_fkey'),
    sa.ForeignKeyConstraint(['weather_date'], ['date_dimension.weather_date'], name='date_dim_weather_date_fkey'),
    sa.PrimaryKeyConstraint('airport_code', 'weather_date')
    )
    op.create_index('idx_weather_date', 'daily_weather_metrics', ['weather_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_weather_date', table_name='daily_weather_metrics')
    op.drop_table('daily_weather_metrics')
    op.drop_table('date_dimension')
    # ### end Alembic commands ###
