"""locations table

Revision ID: fa909d9d44aa
Revises: 172bf7bfe5fa
Create Date: 2026-07-04 16:02:27.931249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa909d9d44aa'
down_revision: Union[str, Sequence[str], None] = '172bf7bfe5fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('airport_code', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('airport_code')
    )
    op.create_foreign_key('ingested_files_airport_code_fkey', 'ingested_files', 'locations', ['airport_code'], ['airport_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ingested_files_airport_code_fkey', 'ingested_files', type_='foreignkey')
    op.drop_table('locations')
    # ### end Alembic commands ###
